### ISSUE TITLE
Если указать sqlite и файл, будет `Cannot operate on a closed database.`

### ISSUE THREAD

**Issue by PerchunPak** [PerchunPak/PingerBot#21]
```py
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
    await self.coro(*args, **kwargs)
  File "/app/src/events.py", line 119, in ping_servers
    servers = self.bot.db.get_servers()
  File "/app/src/database.py", line 175, in get_servers
    return self._execute(select(self.t.ss)).all()
  File "/app/src/decoratore_db_execute.py", line 34, in all
    for result in self.cursor_result.all():
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 1067, in all
    return self._allrows()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 400, in _allrows
    rows = self._fetchall_impl()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 1803, in _fetchall_impl
    return self.cursor_strategy.fetchall(self, self.cursor)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 981, in fetchall
    self.handle_exception(result, dbapi_cursor, e)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 941, in handle_exception
    result.connection._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2026, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/cursor.py", line 977, in fetchall
    rows = dbapi_cursor.fetchall()
sqlalchemy.exc.ProgrammingError: (sqlite3.ProgrammingError) Cannot operate on a closed database.
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by PerchunPak** [comment]
Исправлено после https://github.com/PerchunPak/PingerBot/commit/89a448eb223291d26666845c6994ec4f43288227
